language: php
php:
  - 7.1
service:
  - mysql
before_script:
  - composer install
  - composer dump-autoload
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan vendor:publish
  - mysql -e 'CREATE DATABASE IF NOT EXISTS welcome ;'
  - php artisan migrate
  - php artisan db:seed
script: ./vendor/bin/phpunit